apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: control-plane-binding
subjects:
  - kind: ServiceAccount
    name: control-plane-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: control-plane-role
  apiGroup: rbac.authorization.k8s.io